development:
  adapter: mysql2
  database: developmentdb
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: 127.0.0.1
  encoding: utf8

test:
  adapter: mysql2
  database: safeteam_test
  username: <%= ENV['DATABASE_USERNAME'] || 'root' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'password' %>
  host: 127.0.0.1
  encoding: utf8

production:
  adapter: mysql2
  database: Railsdb
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: 127.0.0.1
  encoding: utf8