development:
  adapter: mysql2
  database: developmentdb
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost
  encoding: utf8

test:
  adapter: mysql2
  database: <%= ENV['DATABASE_NAME'] || 'test' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'root' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'password' %>
  host: localhost
  encoding: utf8

production:
  adapter: mysql2
  database: Railsdb
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost
  encoding: utf8