module BuildingsHelper
  # Dropdown list: returns buildings sorted alphabetically
  def building_dropdown
    building_zone_map.keys.sort
  end

  # Map building names to their corresponding zone
  def building_zone_map
    {
      "College of Public Health Building" => "A_1",
      "Lawton & Rhea Chiles Center" => "A_1",
      "Northwest Education Complex" => "A_1",
      "West Side Conference Center" => "A_1",
      "Children's Medical Services Building" => "A_2",
      "USF Health-Shared Student Administration Building" => "A_2",
      "USF Health-Nursing Building" => "A_2",
      "USF Health-Therapy Building" => "A_2",
      "USF Health-Student Group Learning Building" => "A_3",
      "Johnnie B. Byrd, Sr. Alzheimer's Center" => "C_1",
      "Education Building" => "E_3",
      "Behavioral Sciences Building" => "E_3",
      "Faculty Office Building" => "E_3",
      "Human Services Architecture Building" => "E_3",
      "WUSF Television Station" => "E_3",
      "WUSF - FM 89.7 Radio Building" => "E_3",
      "Communication & Information Sciences Building" => "E_4",
      "C. H. Ferguson Hall (Business Administration)" => "E_4",
      "Russell M. Cooper Hall (Arts & Sciences)" => "E_4",
      "Patel Center for Global Solutions" => "E_5",
      "Sam & Martha Gibbons Alumni Center" => "E_5",
      "Lifsey House & President's Residence" => "E_5",
      "Moffitt Cancer Center and Research Institute" => "B_2",
      "Moffitt Clinical Support Building" => "B_2",
      "Northwest Chiller Plant" => "B_2",
      "Moffitt Research Center" => "B_2",
      "Moffitt Clinic Building" => "B_2",
      "Shriners Children's Hospital" => "B_3",
      "Moffitt Faculty Office Building" => "B_3",
      "Moffitt Parking Garage #1" => "B_2",
      "Moffitt Parking Garage #2" => "B_3",
      "Hope Lodge - American Cancer Society" => "B_3",
      "William G. Doc Myers Building (Florida Dept of Health)" => "B_4",
      "University Diagnostic Institute (Research Park)" => "B_5",
      "Cypress Suites (RCA-RCB)" => "E_2",
      "Endeavor Hall (The Village)" => "E_2",
      "Kosove Hall" => "E_2",
      "Pinnacle Hall (The Village)" => "E_2",
      "Student Health Services Building" => "E_2",
      "Argos Center" => "E_2",
      "Betty Castor Hall" => "E_2",
      "Beta Hall" => "E_2",
      "Holly Drive Apartments (HAA-HAM)" => "E_2",
      "Fine Arts - Dance Building" => "D_2",
      "Fine Arts Building" => "C_3",
      "Fine Arts Studio" => "C_2",
      "Music Building" => "C_2",
      "Psych./Communication Science & Disorders Building" => "C_2",
      "Parking & Transportation Building A" => "C_2",
      "Parking & Transportation Building B" => "C_2",
      "USF Tampa Bookstore" => "D_2",
      "Theatre Centre" => "D_2",
      "Theatre Auditorium - Theatre I" => "D_2",
      "Theatre II" => "D_2",
      "USF Post Office" => "D_2",
      "Facilities Management" => "D_2",
      "Central Plant" => "D_2",
      "FIT Health & Wellness Center (The Village)" => "D_2",
      "Phyllis P. Marshall Student Center (Student Union)" => "D_2",
      "Cypress Apartments (RCC-RCE)" => "E_1",
      "Summit Hall (The Village)" => "E_1",
      "The Hub Dining Hall (The Village)" => "E_1",
      "Publix Supermarket" => "E_1",
      "University Police Building" => "E_1",
      "Beacon Hall (The Village)" => "D_1",
      "Horizon Hall (The Village)" => "D_1",
      "USF Federal Credit Union" => "D_1",
      "Testbed for Assistive Rehabilitative Robotics Building" => "D_1",
      "C. W. Bill Young Hall" => "F_3",
      "Recreation Activities Center" => "F_3",
      "Physical Education Building" => "F_3",
      "Track & Field Stadium" => "F_3",
      "Champion's Choice Dining" => "F_4",
      "Fowler Fields Pavilion" => "F_5",
      "Pam & Les Muma Basketball Center" => "F_4",
      "Yuengling Center" => "F_4",
      "USF/Patel Partnership School" => "F_5",
      "Baseball Complex & Dugouts" => "G_4",
      "Softball Complex & Dugouts" => "G_4",
      "Corbett Soccer Park Stadium" => "G_4",
      "USF Preschool for Creative Learning" => "G_4",
      "Crosswinds Wesley Foundation" => "G_3",
      "Chapel Center" => "G_3",
      "Baptist Student Center" => "G_2",
      "Hillel Jewish Student Center" => "G_2",
      "Anthony J. Pizzo Elementary School" => "G_5",
      "Laurel Drive Parking Garage" => "C_1",
      "Botanical Gardens Office" => "A_4",
      "Magnolia Apartments (MAA-MAH)" => "C_4",
      "Betty Castor Hall" => "E_2"
    }.sort.to_h
  end
end
