module BuildingsHelper
  # Dropdown list: returns buildings sorted alphabetically
  def building_dropdown
    building_zone_map.keys.sort
  end

  # Map building names to their corresponding zone
  def building_zone_map
    {
      "CPH - College of Public Health" => "A_1",
      "LRC - Lawton & Rhea Chiles Center" => "A_1",
      "Northwest Education Complex" => "A_1",
      "MHA - West Side Conference Center" => "A_1",
      "CMS - Children's Medical Services" => "A_2",
      "USF Health-Shared Student Administration Building" => "A_2",
      "USF Health-Nursing Building" => "A_2",
      "USF Health-Therapy Building" => "A_2",
      "MDL - USF Health-Student Group Learning Building" => "A_3",
      "ALZ - Johnnie B. Byrd, Sr. Alzheimer's Center" => "C_1",
      "EDU - Education Building" => "E_3",
      "BEH - Behavioral Sciences" => "E_3",
      "FAO - Faculty Office Building" => "E_3",
      "HMS - Human Services/Architecture Building" => "E_3",
      "TVB - WUSF Television Station" => "E_3",
      "WRB - WUSF - FM 89.7 Radio Building" => "E_3",
      "CIS - Communication & Information Sciences" => "E_4",
      "BSN - C. H. Ferguson Hall (Business Admin.)" => "E_4",
      "CPR - Cooper Hall (Arts & Sciences)" => "E_4",
      "LIB - Library" => "E_4",
      "CGS - Patel Center for Global Solutions" => "E_5",
      "Sam & Martha Gibbons Alumni Center" => "E_5",
      "Lifsey House & President's Residence" => "E_5",
      "Moffitt Cancer Center and Research Institute" => "B_2",
      "Moffitt Clinical Support Building" => "B_2",
      "Northwest Chiller Plant" => "B_2",
      "MRC - Moffitt Research Center" => "B_2",
      "MCB - Moffitt Clinic Building" => "B_2",
      "Shriners Children's Hospital" => "B_3",
      "Moffitt Faculty Office Building" => "B_3",
      "Moffitt Parking Garage #1" => "B_2",
      "Moffitt Parking Garage #2" => "B_3",
      "Hope Lodge - American Cancer Society" => "B_3",
      "William G. Doc Myers Building (Florida Dept of Health)" => "B_4",
      "University Diagnostic Institute (Research Park)" => "B_5",
      "Cypress Suites (RCA-RCB)" => "E_2",
      "Endeavor Hall (The Village)" => "E_2",
      "Kosove Hall" => "E_2",
      "Pinnacle Hall (The Village)" => "E_2",
      "Student Health Services Building" => "E_2",
      "Argos Center" => "E_2",
      "Betty Castor Hall" => "E_2",
      "Beta Hall" => "E_2",
      "HAA-HAM (Holly Drive Apartments)" => "E_2",
      "FAD - Fine Arts - Dance Building" => "D_2",
      "FAH - Fine Arts Building" => "C_3",
      "FAS - Fine Arts Studio" => "C_2",
      "MUS - Music Building" => "C_2",
      "PCD - Psych./Comms Science & Disorders Building" => "C_2",
      "Parking & Transportation Building A" => "C_2",
      "Parking & Transportation Building B" => "C_2",
      "USF Tampa Bookstore" => "D_2",
      "Theatre Centre" => "D_2",
      "Theatre Auditorium - Theatre I" => "D_2",
      "Theatre II" => "D_2",
      "USF Post Office" => "D_2",
      "Facilities Management" => "D_2",
      "Central Plant" => "D_2",
      "FIT Health & Wellness Center (The Village)" => "D_2",
      "Phyllis P. Marshall Student Center (Student Union)" => "D_2",
      "Cypress Apartments (RCC-RCE)" => "E_1",
      "Summit Hall (The Village)" => "E_1",
      "The Hub Dining Hall (The Village)" => "E_1",
      "Publix Supermarket" => "E_1",
      "University Police Building" => "E_1",
      "Beacon Hall (The Village)" => "D_1",
      "Horizon Hall (The Village)" => "D_1",
      "USF Federal Credit Union" => "D_1",
      "Testbed for Assistive Rehabilitative Robotics Building" => "D_1",
      "C. W. Bill Young Hall" => "F_3",
      "Recreation Activities Center" => "F_3",
      "Physical Education Building" => "F_3",
      "Track & Field Stadium" => "F_3",
      "Champion's Choice Dining" => "F_4",
      "Fowler Fields Pavilion" => "F_5",
      "Pam & Les Muma Basketball Center" => "F_4",
      "Yuengling Center" => "F_4",
      "USF/Patel Partnership School" => "F_5",
      "Baseball Complex & Dugouts" => "G_4",
      "Softball Complex & Dugouts" => "G_4",
      "Corbett Soccer Park Stadium" => "G_4",
      "USF Preschool for Creative Learning" => "G_4",
      "Crosswinds Wesley Foundation" => "G_3",
      "Chapel Center" => "G_3",
      "Baptist Student Center" => "G_2",
      "Hillel Jewish Student Center" => "G_2",
      "Anthony J. Pizzo Elementary School" => "G_5",
      "Laurel Drive Parking Garage" => "C_1",
      "Botanical Gardens Office" => "A_4",
      "Magnolia Apartments (MAA-MAH)" => "C_4",
      "Betty Castor Hall" => "E_2"
    }.sort.to_h
  end

  # Map zone to corresponding address
  def zone_to_address(zone)
    addresses = {
      "A_1" => "3010 USF Banyan Circle Tampa, FL 33612",
      "A_2" => "12901 Bruce B. Downs Blvd, Tampa, FL",
      "A_3" => "12908 USF Hawthorn Dr, Tampa, FL 33612",
      "A_4" => "12210 USF Pine Drive, Tampa, FL 33612",
      "B_1" => "13301 Bruce B Downs Blvd, Tampa, FL 33612",
      "B_2" => "12902 USF Magnolia Drive, Tampa, FL 33612",
      "B_3" => "14200 USF Magnolia Drive, Tampa, FL 33612",
      "B_4" => "3602 Spectrum Blvd, Tampa, FL 33612",
      "B_5" => "3301 USF Alumni Drive, Tampa, FL 33612",
      "C_1" => "13325 USF Laurel Dr, Tampa, FL 33620",
      "C_2" => "3755 USF Holly Drive MUS 101, Tampa, FL 33620",
      "C_3" => "12037 USF Beard Drive, Tampa, FL 33620",
      "C_4" => "12033 USF Beard Drive, Tampa FL 33620",
      "C_5" => "3720 Spectrum Blvd, Tampa, FL 33612",
      "D_1" => "4204 USF Mulberry Lane Tampa, FL 33620",
      "D_2" => "4103 Cedar Circle Tampa, FL 33620",
      "D_3" => "12100 Leroy Collins Blvd. Tampa, FL 33620",
      "D_4" => "4101 USF Apple Dr, Tampa, FL 33620",
      "D_5" => "3814 Spectrum Blvd, Tampa, FL 33612",
      "E_1" => "4303 USF Dogwood Dr, Tampa, FL 33620",
      "E_2" => "4302 USF Holly Drive Tampa, FL 33620",
      "E_3" => "4205 USF Willow Dr, Tampa, FL 33620",
      "E_4" => "4202 E Fowler Ave, Tampa, Florida 33620",
      "E_5" => "11810 USF Sago Drive Tampa, FL 33620",
      "F_1" => "4747 USF Birch Dr, Tampa, FL 33620",
      "F_3" => "12301 USF Genshaft Dr, Tampa, FL 33620",
      "F_4" => "12560 USF Bull Run Dr. Tampa, FL 33620",
      "F_5" => "11801 USF Bull Run Drive, Tampa, FL 33620",
      "G_2" => "13110 N 50th St, Tampa, FL 33620",
      "G_3" => "12850 N 50th St. Tampa, FL 33617",
      "G_4" => "11811 USF Bull Run Drive, Tampa, FL 33620",
      "G_5" => "11701 USF Bull Run Drive, Tampa, FL 33620"
    }
    addresses[zone] || "Address not found"
  end
end
